### ISSUE TITLE
First Milestone 

### ISSUE THREAD

**Issue by CristynaBC** [CristynaBC/SAP010-md-links#1]
Estudo:
- NodeJS: 
 - [ ] Learn you the Node 

- [ ] How to NPM 

- [ ] Promise It Wont Hurt

- Projeto

- [ ] Ler um arquivo e imprimir o conteúdo com console.log

**Comment by CristynaBC** [comment]
Learn You Node : https://github.com/workshopper/learnyounode 
How to NPM: https://github.com/workshopper/how-to-npm
Promise it Wont Hurt: https://github.com/stevekane/promise-it-wont-hurt

**Comment by CristynaBC** [comment]
- FileSystem:

1.  fs.readFile
2.  fs.stat
3.  fs.readDirSync

- path

1. path.extname

 -  CommomJS Modules
 -
