### ISSUE TITLE
Checklist Completo do projeto

### ISSUE THREAD

**Issue by CristynaBC** [CristynaBC/SAP010-md-links#2]
**Geral**
 

- [x] Poder instalar via npm install --global <github-user>/md-links

**README.md**
 

- [x] Um board com o backlog das implementações da sua biblioteca

 

- [x] Documentação técnica da sua biblioteca

 

- [x] Guia de uso e instalação da biblioteca

**API mdLinks(path, opts)**

- [x]  O módulo exporta uma função com a interface (API) esperada

 

- [x] Implementa suporte para arquivo individual

 

- [x] Implementa suporte para diretórios

 

- [x] Implementa options.validate

**CLI**
 

- [x] Possuir o executável md-links no path (configurado no package.json)

 

- [x] Executar sem erros e ter o resultado esperado

 

- [x] Implementar --validate

 

- [x] Implementar --stats

**Testes**
 

- [x] Os testes unitários devem cobrir no mínimo 70% dos statements, functions, lines e branches.

 

- [x] Rodar os testes e linter (npm test).

**Extra**

- [x] Instalar Chalk para colorir o terminal
